### ISSUE TITLE
FEZ location fix and Nuclear Throne location

### ISSUE THREAD

**Issue by BlueScarredJaguar** [Tux1c/LGSO#10]
You wrote in the .txt that FEZ's location is '/.local/share/Fez' , but it isn't; The location has FEZ capitalized ('/.local/share/FEZ').
Nuclear Throne's game save and config location on Steam is at '~/.config/share/nuclearthrone'.

**Comment by Tux1c** [comment]
Hey, 

sorry for late reply and thank you so much for your report ;)
