### ISSUE TITLE
Empire: Total War savegame folder

### ISSUE THREAD

**Issue by ariacorrente** [Tux1c/LGSO#14]
Name of the game: Empire: Total War
Platform (Steam, GOG, etc.): Steam
Full save location: $HOME/.local/share/feral-interactive/Empire

Name of the game: Jagged Alliance Flashback
Platform (Steam, GOG, etc.): Steam
Full save location: $HOME/.config/unity3d/Full Control/Jagged Alliance Flashback

From the README:

> If you have a game save location to suggest, please use the "SAVE" tag

I don't know how to tag with "SAVE", I hope this is enough.

**Comment by Tux1c** [comment]
Yes, thank you very much for your input :) Closing & tagging.
