### ISSUE TITLE
Sorry, Nuclear Throne location fix

### ISSUE THREAD

**Issue by BlueScarredJaguar** [Tux1c/LGSO#15]
I am extremely sorry, in my issue I didn't write the correct location of the Nuclear Throne save location; I have accidentally added a directory called 'share' to the path, which doesn't exist - the location of the save is '~/.config/nuclearthrone', not '~/.config/share/nuclearthrone'.

Thank you and apologies once again,
Stav

**Comment by Tux1c** [comment]
np man, all good :)
Thanks for your input, fixed :)
