### ISSUE TITLE
The Basement Collection save path

### ISSUE THREAD

**Issue by etam** [Tux1c/LGSO#7]
The save path for "The Basement Collection" is set to ".macromedia/Flash_Player/#SharedObjects". This is wrong. There are stored all data for every website that uses flash.

**Comment by Tux1c** [comment]
Hi Etam,

Thank you for your report! I have removed The Basement Collection from the list in commit number 27bcbf91af79d7160f7af08af9e675d19aaf95ee.

Have a nice day, and thank you again!
