### ISSUE TITLE
no easter eggs

### ISSUE THREAD

**Issue by Shpitzick** [Tux1c/LGSO#9]
yan00b

**Comment by Qsuare** [comment]
not free as in freedom enough

**Comment by Tux1c** [comment]
Hello dearest friends @Shpitzick  @Qsuare,

Please refrain from spamming my project. That creates unneeded mess and confusion for myself and the others.

I will mark that as closed now,
Tux1c.

**Comment by Shpitzick** [comment]
lol what a dick
